version: '3.8'

services:
  react-native:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    volumes:
      - .:/src
      - /src/node_modules
    env_file:
      - .env
    command: npx react-native start
