name: CI React Native Smart Survey

on:
  push:
    branches:
      - '**' # Will run on all branches

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Docker Image
        run: docker pull naeljeff/smartsurvey:v0.1.0
      
      - name: Start Container
        run: docker run -d -p 8081:8081 naeljeff/smartsurvey:v0.1.0
      
      - name: Install npm dependencies
        run: |
          sudo chown -R $USER:$USER ./
          npm install
      
      - name: Run test cases
        run: npm test