name: CI React Native Smart Survey

on:
  push:
    branches:
      - '**' # Will run on all branches

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Docker Image
        run: docker pull naeljeff/smartsurvey:v0.1.0

      - name: Start Container
        run: docker run -d -p 8081:8081 naeljeff/smartsurvey:v0.1.0

      - name: Install npm dependencies
        run: |
          sudo chown -R $USER:$USER ./
          npm install

      - name: Run test cases
        run: npm test

  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Install npm dependencies
        run: |
          sudo chown -R $USER:$USER ./
          npm install

      - name: Build android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: smart-survey.apk
          path: android/app/build/outputs/apk/release/app-release.apk
