name: Run Smart Survey Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 8081:8081

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Docker Container
        run: |
          docker-compose up --build -d

      - name: Install Dependencies
        run: docker-compose exec -T react-native npm install

      - name: Run Tests
        run: docker-compose exec -T react-native npm test

      - name: Stop Docker Container
        run: docker-compose down

    strategy:
      matrix:
        node-version: [20]
